query GetAllDocs($workspaceId: uuid!) {
    blocks(
        where: {
            workspace_id: { _eq: $workspaceId }
            type: { _eq: "page" }
            deleted_at: { _is_null: true }
        }
        order_by: { updated_at: desc }
    ) {
        id
        content
        cover_image
        created_at
        updated_at
        workspace_id
        user_id
        folder {
            id
            name
        }
        sub_blocks(order_by: { position: asc }, limit: 10) {
            id
            type
            content
            tasks {
                id
                status
                schedule_date
                deadline_date
            }
        }
    }
}

query GetDocumentBlocks($pageId: uuid!) {
    blocks(
        where: {
            _or: [{ id: { _eq: $pageId } }, { page_id: { _eq: $pageId } }]
            deleted_at: { _is_null: true }
        }
        order_by: { position: asc }
    ) {
        id
        content
        cover_image
        position
        parent_id
        page_id
        type
        workspace_id
        user_id
        created_at
        updated_at
        link_access {
            permission_type
        }
        tasks {
            id
            status
            deadline_date
            schedule_date
            priority
            user_id
        }
    }
}

query GetDocsCount($workspaceId: uuid!) {
    blocks_aggregate(
        where: {
            workspace_id: { _eq: $workspaceId }
            type: { _eq: "page" }
            deleted_at: { _is_null: true }
        }
    ) {
        aggregate {
            count
        }
    }
}

query GetSharedWithMeDocs($userId: uuid!) {
    blocks(
        where: {
            type: { _eq: "page" }
            deleted_at: { _is_null: true }
            access_requests: {
                requester_id: { _eq: $userId }
                status: { _eq: "approved" }
            }
        }
        order_by: { updated_at: desc }
    ) {
        id
        content
        cover_image
        created_at
        updated_at
        user_id
        workspace_id
        folder {
            id
            name
        }
        sub_blocks(order_by: { position: asc }, limit: 10) {
            id
            type
            content
            position
            tasks {
                id
                status
                schedule_date
                deadline_date
            }
        }
        access_requests(where: { requester_id: { _eq: $userId } }) {
            permission_type
            status
        }
    }
}
