query GetFolders($workspaceId: uuid!) {
    folders(
        order_by: { created_at: desc }
        where: { workspace_id: { _eq: $workspaceId } }
    ) {
        id
        name
        description
        color
        icon
        parent_id
        created_at
        blocks_aggregate(
            where: { type: { _eq: "page" }, deleted_at: { _is_null: true } }
        ) {
            aggregate {
                count
            }
        }
    }
}

query GetFolderById($folderId: uuid!) {
    folders_by_pk(id: $folderId) {
        id
        name
        description
        color
        icon
        parent_id
        created_at
        workspace_id
        children(order_by: { created_at: desc }) {
            id
            name
            description
            color
            icon
            created_at
            blocks_aggregate(
                where: { type: { _eq: "page" }, deleted_at: { _is_null: true } }
            ) {
                aggregate {
                    count
                }
            }
        }
        blocks(
            where: { type: { _eq: "page" }, deleted_at: { _is_null: true } }
            order_by: { updated_at: desc }
        ) {
            id
            content
            cover_image
            created_at
            updated_at
            workspace_id
            user_id
            document_stars {
                document_id
            }
            folder {
                id
                name
            }
            sub_blocks(order_by: { position: asc }, limit: 10) {
                id
                type
                content
                tasks {
                    id
                    status
                    schedule_date
                    deadline_date
                }
            }
        }
    }
}
