mutation CreateAccessRequest($input: access_requests_insert_input!) {
    insert_access_requests_one(
        object: $input
        on_conflict: {
            constraint: access_requests_document_id_requester_id_key
            update_columns: [permission_type, status, message, updated_at]
        }
    ) {
        id
    }
}

mutation RequestEditAccess(
    $documentId: uuid!
    $requesterId: uuid!
    $message: String!
    $updatedAt: timestamptz!
) {
    update_access_requests(
        where: {
            document_id: { _eq: $documentId }
            requester_id: { _eq: $requesterId }
            permission_type: { _eq: "read" }
            status: { _eq: "approved" }
        }
        _set: {
            message: $message
            permission_type: "write"
            status: "pending"
            updated_at: $updatedAt
        }
    ) {
        affected_rows
    }
}

mutation BulkDeleteAccessRequests(
    $document_ids: [uuid!]!
    $requester_id: uuid!
) {
    delete_access_requests(
        where: {
            document_id: { _in: $document_ids }
            requester_id: { _eq: $requester_id }
        }
    ) {
        affected_rows
    }
}
