mutation CreateTask($input: tasks_insert_input!) {
    insert_tasks_one(object: $input) {
        id
        block_id
        user_id
        status
        deadline_date
        schedule_date
        priority
        created_at
        updated_at
    }
}

mutation UpdateTask($id: uuid!, $input: tasks_set_input!) {
    update_tasks_by_pk(pk_columns: { id: $id }, _set: $input) {
        id
        block_id
        user_id
        status
        deadline_date
        schedule_date
        priority
        created_at
        updated_at
    }
}

mutation UpdateTaskDetails(
    $id: uuid!
    $taskInput: tasks_set_input!
    $blockId: uuid!
    $blockInput: blocks_set_input!
) {
    update_tasks_by_pk(pk_columns: { id: $id }, _set: $taskInput) {
        id
        schedule_date
        deadline_date
        priority
    }
    update_blocks_by_pk(pk_columns: { id: $blockId }, _set: $blockInput) {
        id
        content
        page_id
    }
}
